# Generated by Django 2.2.5 on 2021-01-16 17:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(db_column='GUID', max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='NAME', max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('mail', models.EmailField(db_column='MAIL', max_length=254)),
                ('score', models.FloatField(db_column='USER_SCORE')),
            ],
            options={
                'db_table': 'USER',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.CharField(db_column='MESID', max_length=20, primary_key=True, serialize=False)),
                ('context', models.CharField(db_column='CONTEXT', max_length=1000)),
                ('sendtime', models.DateTimeField(db_column='SENDTIME', default=django.utils.timezone.now)),
                ('sender', models.ForeignKey(db_column='SENDERID', on_delete=django.db.models.deletion.CASCADE, to='blog.User')),
            ],
            options={
                'db_table': 'MESSAGE',
            },
        ),
    ]
