# Generated by Django 2.2.5 on 2021-01-19 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('advert_id', models.CharField(db_column='ADVERTID', max_length=20, primary_key=True, serialize=False)),
                ('advert_name', models.CharField(db_column='ADVERTNAME', max_length=100)),
                ('price', models.IntegerField(db_column='PRICE')),
                ('summary', models.CharField(db_column='ADVSUMMARY', max_length=500)),
            ],
            options={
                'db_table': 'ADVERT',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.ForeignKey(db_column='CUSID', max_length=20, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='blog.User')),
            ],
            options={
                'db_table': 'CUSTOMER',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.CharField(db_column='SERVICEID', max_length=20, primary_key=True, serialize=False)),
                ('service_name', models.CharField(db_column='SERVİCENAME', max_length=20)),
                ('summary', models.CharField(db_column='SERVSUMMARY', max_length=500)),
            ],
            options={
                'db_table': 'SERVICE',
            },
        ),
        migrations.CreateModel(
            name='ServiceOffer',
            fields=[
                ('service_offer_id', models.CharField(db_column='SERVICEOFFID', max_length=20, primary_key=True, serialize=False)),
                ('customer_conditions', models.CharField(db_column='CUSTOMERCOND', max_length=100)),
                ('satisfaction_id', models.CharField(db_column='SATISFACTIONID', max_length=20)),
                ('adver_id', models.ForeignKey(db_column='ADVERID', on_delete=django.db.models.deletion.CASCADE, to='blog.Advert')),
                ('purchaser', models.ForeignKey(db_column='PURCHASERID', on_delete=django.db.models.deletion.CASCADE, to='blog.Customer')),
            ],
            options={
                'db_table': 'SERVICEOFFER',
            },
        ),
        migrations.CreateModel(
            name='ServiceSatisfaction',
            fields=[
                ('service_satisfaction_id', models.CharField(db_column='SERVICESATID', max_length=20, primary_key=True, serialize=False)),
                ('customer_performance', models.IntegerField(db_column='CUSTOMERSCORE')),
                ('provider_performance', models.IntegerField(db_column='PROVIDERSCORE')),
                ('off_id', models.ForeignKey(db_column='OFFID', max_length=20, on_delete=django.db.models.deletion.CASCADE, to='blog.ServiceOffer')),
            ],
            options={
                'db_table': 'SERVICESATISFACTION',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('provider_id', models.ForeignKey(db_column='PROID', max_length=20, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='blog.User')),
                ('location', models.CharField(db_column='LOCATION', max_length=100)),
                ('experience', models.IntegerField(db_column='EXP')),
                ('speciality', models.ForeignKey(db_column='SPECIALITYID', on_delete=django.db.models.deletion.CASCADE, to='blog.Service')),
            ],
            options={
                'db_table': 'PROVIDER',
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mess_id', models.ForeignKey(db_column='MESSID', max_length=20, on_delete=django.db.models.deletion.CASCADE, to='blog.Message')),
                ('offer_id', models.ForeignKey(db_column='OFID', max_length=20, on_delete=django.db.models.deletion.CASCADE, to='blog.ServiceOffer')),
            ],
        ),
        migrations.CreateModel(
            name='Advertisements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adv_id', models.ForeignKey(db_column='ADVID', max_length=20, on_delete=django.db.models.deletion.CASCADE, to='blog.Advert')),
                ('pro_id', models.ForeignKey(db_column='PROID', max_length=20, on_delete=django.db.models.deletion.CASCADE, to='blog.Provider')),
            ],
            options={
                'db_table': 'ADVERTISEMENTS',
            },
        ),
        migrations.AddField(
            model_name='advert',
            name='prov_id',
            field=models.ForeignKey(db_column='PROVID', max_length=20, on_delete=django.db.models.deletion.CASCADE, to='blog.Provider'),
        ),
    ]
