# Generated by Django 2.2.5 on 2021-01-19 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210119_2046'),
    ]

    operations = [
        migrations.CreateModel(
            name='SatisfactionFails',
            fields=[
                ('satisfaction_id', models.CharField(db_column='SATISFACID', max_length=20, primary_key=True, serialize=False)),
                ('failure', models.CharField(db_column='FAILURE', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(db_column='CATEGORY', default='Undefined', max_length=20),
        ),
        migrations.AddField(
            model_name='serviceoffer',
            name='status',
            field=models.CharField(db_column='STATUS', default='Undetermined', max_length=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.OneToOneField(db_column='CUSID', max_length=20, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='blog.User'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='provider_id',
            field=models.OneToOneField(db_column='PROID', max_length=20, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='blog.User'),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('session_id', models.CharField(db_column='SESSIONID', max_length=20, primary_key=True, serialize=False)),
                ('session_date', models.DateField(db_column='SESSIONDATE')),
                ('hour', models.IntegerField(db_column='SESSIONHOUR')),
                ('customer_id', models.ForeignKey(db_column='CUSTID', max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Customer')),
                ('expert_id', models.ForeignKey(db_column='EXPERTID', max_length=20, on_delete=django.db.models.deletion.CASCADE, to='blog.Provider')),
            ],
            options={
                'db_table': 'SCHEDULE',
            },
        ),
        migrations.CreateModel(
            name='OfferSessions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_id', models.ForeignKey(db_column='SOFFERID', on_delete=django.db.models.deletion.CASCADE, to='blog.ServiceOffer')),
                ('session_id', models.ForeignKey(db_column='OFFERID', on_delete=django.db.models.deletion.CASCADE, to='blog.Schedule')),
            ],
            options={
                'db_table': 'OFFERSESSION',
            },
        ),
    ]
